### ISSUE TITLE
How to reference bibtex-autocomplete

### ISSUE THREAD

**Issue by edzob** [dlesbre/bibtex-autocomplete#10]
I would like to add bibtex-autocomplete to the contribution section of my paper.

If I am not misstaken, then this is not yet possible from this great project.

There are various ways to support this 

via Zenodo (see for example ASReview https://zenodo.org/records/10203469, and for example these stackoverflow items https://academia.stackexchange.com/questions/151533/how-to-cite-a-github-repository-that-i-used-for-data-collection-research-paper, https://academia.stackexchange.com/questions/14010/how-do-you-cite-a-github-repository 

or directly via GitHub.

@dlesbre would you be okay to support one of these two options?
or can I assist in some way or another? 

I would love to reference your great work. 
Regards Edzo

**Comment by dlesbre** [comment]
Thanks for your interest in my project! You're right, I'd not given much thought to anyone citing this.
I've uploaded it to Zenodo as suggested https://zenodo.org/records/10207745 and added a CITATION.cff file here as well. That should cover all needs, let me know if it doesn't.

Note that both the Zenodo and github file point to the latest version (1.2.2, released today 2023-11-26), but changes with the previous version are minor.

**Comment by edzob** [comment]
@dlesbre wauw.. that is fast. Thank you so much :)

**Comment by dlesbre** [comment]
Believe it or not, I was planning on working a bit on btac yesterday and getting around to releasing the few changes I'd made.
