### ISSUE TITLE
btac removes capitalization

### ISSUE THREAD

**Issue by KonradHoeffner** [dlesbre/bibtex-autocomplete#11]
For example, `title = {{HermiT}: {A}n {OWL} 2 reasoner},` becomes `title = {HermiT: An OWL 2 reasoner},`, which some bibliography styles incorrectly format in all lower case.
Is there a way to tell btac to keep the capitalization in place?

**Comment by dlesbre** [comment]
Thanks for reporting this. Its a bug, `btac` is meant to keep these around, in fact it is meant to leave all present fields unchanged. I've identified the culprit but it might take me a while to fix since I'm a bit busy right now.

**Comment by dlesbre** [comment]
I've uploaded a new version (1.3.0) that fixes this issue. I've also added new command line option (`--fp / --protect-uppercase <field>`, `--FP / --dont-protect-uppercase <field>` and `--fpa / --protect-all-uppercase`) to auto-insert such protection in the new fields.
