### ISSUE TITLE
bibtext compatible articles

### ISSUE THREAD

**Issue by matee911** [dlesbre/bibtex-autocomplete#13]
Hi, I see that btac adds `publisher` to `@article` entry type.
It's not compatible neither with [BibTeX](https://www.bibtex.com/f/publisher-field/) nor BiBLaTeX.

Invocation of `biber --validate-datamodel thesis` yields warnings about invalid field.

i.e. `WARN - Datamodel: article entry 'teokarevic2011ten' (refs.bib): Invalid field 'publisher' for entrytype 'article'` which indeed is not required by APA style.

Do you think `--strict` mode could be implemented?

**Comment by dlesbre** [comment]
I've added this feature in 1.3.2. The new option is `--filter-fields-by-entrytype` or `-b` for short. It takes a single argument: either `required` (only add fields marked as required), `optional` (required and optional fields) and `all` (require, optional, and non-standard fields like `doi`, `issn`, `isbn`).

I used [this list](https://tex.stackexchange.com/questions/239042/where-can-we-find-a-list-of-all-available-bibtex-entries-and-the-available-fiel) as reference of what fields are required/optional by entrytype. Note that this is restricted to bibtex's fields and entrytypes, not biblatex's extension.
