### ISSUE TITLE
Output to file immediately?

### ISSUE THREAD

**Issue by homocomputeris** [dlesbre/bibtex-autocomplete#18]
Can btac stream results to the output file immediately? Sometimes it hangs on, say, 92% for hours, and there is no output file.

Alternatively, where are the intermediate results are stored?

**Comment by dlesbre** [comment]
Intermediate results are only stored in RAM at the moment. However, if you interrupt the program by Ctrl+C, it should dump everything to a new temporary file, whose path is printed on the terminal.

**Comment by homocomputeris** [comment]
> it should dump everything to a new temporary file, whose path is printed on the terminal.

Does it contain all entries or only the processed ones?

**Comment by dlesbre** [comment]
It contains all entries, so its safe to replace your input file with the dump. It should tell you how many were completed (which isn't very convenient I know, I'm working on changing it to show the id of the last completed entry).

Note that if you run btac on multiple files, it also concatenates all files into a single one.

**Comment by homocomputeris** [comment]
Great, thanks a lot!
