### ISSUE TITLE
Mistakes / Inaccuracies

### ISSUE THREAD

**Issue by tomkoenecke** [dlesbre/bibtex-autocomplete#5]
Dropping a few mistakes the tool made for my `.bib`-file

Reference management is by no means a trivial task, which no one has mastered to automate yet, but maybe this gets this project one step closer ;)

---

Original reference, pointing to [this book](https://books.google.de/books?hl=de&lr=&id=GEvUBwAAQBAJ&oi=fnd&pg=PA1&dq=dubois+possibility+theory+2012&ots=wyILnNIcc2&sig=nO2cQFjrmgogxdgUjccLvjQ6qR8#v=onepage&q=dubois%20possibility%20theory%202012&f=false).
@book{Dubois2012,
    author = {Dubois, Didier and Prade, Henri},
    publisher = {Springer Science \& Business Media},
    title = {Possibility Theory: An Approach to Computerized Processing of Uncertainty},
    year = {2012}
}

Autocompleted version with a nonexistent doi, and a journal as booktitle?
@book{Dubois2012,
	title = {Possibility Theory: An Approach to Computerized Processing of Uncertainty},
	author = {Dubois, Didier and Prade, Henri},
	booktitle = {Journal of the American Society for Information Science},
	doi = {10.1007/978-1-4684-5287-7},
	issn = {0002-8231},
	month = {3},
	pages = {1-263},
	publisher = {Springer Science & Business Media},
	year = {2012},
}

---

Original reference, meaning [this book](https://scholar.google.de/scholar?hl=de&as_sdt=0%2C5&q=augustin+introduction+to+imprecise+probabilities&btnG=&oq=augustin+introduction+to+imprecise+probab)
@book{Augustin2014,
    author = {Augustin, Thomas and Coolen, Frank PA and De Cooman, Gert and Troffaes, Matthias CM},
    publisher = {John Wiley \& Sons},
    title = {Introduction to imprecise probabilities},
    year = {2014}
}

Autocompleted version with a doi pointing to a paper from different authors
@book{Augustin2014,
	title = {Introduction to imprecise probabilities},
	author = {Augustin, Thomas and Coolen, Frank PA and De Cooman, Gert and Troffaes, Matthias CM},
	booktitle = {Optimization Under Uncertainty with Applications to Aerospace Engineering},
	doi = {10.1007/978-3-030-60166-9_2},
	isbn = {9783030601652},
	issn = {1940-6517},
	month = {5},
	pages = {35-79},
	publisher = {John Wiley & Sons},
	year = {2014},
}

**Comment by dlesbre** [comment]
I've made a few changes in version 1.1.2 that should fix those issues:
- Entries with no common authors will no longer match (provided both your bib entry and the online one has at least one author)
- Entries with many common authors will be prioritized
- I added some logic to dispatch crossref and unpaywall ambiguous `container-title` between the `journal` field and the `booktitle` field
- I added a sanity check on DOI and URL fields. They will only be adde if the values resolve/redirect to a valid url.
