### ISSUE TITLE
`btac` command not found on windows

### ISSUE THREAD

**Issue by schulzch** [dlesbre/bibtex-autocomplete#6]
When installing via `pip install bibtexautocomplete` the pip copies `btac` to `Scripts`. However, windows requires a `btac.exe` (or .cmd) in that folder to work properly.

According to [this reference](https://packaging.python.org/en/latest/guides/distributing-packages-using-setuptools/?highlight=console_scripts%20#scripts):

> Although setup() supports a [scripts](https://docs.python.org/3/distutils/setupscript.html#distutils-installing-scripts) keyword for pointing to pre-made scripts to install, the recommended approach to achieve cross-platform compatibility is to use [console_scripts](https://packaging.python.org/en/latest/guides/distributing-packages-using-setuptools/?highlight=console_scripts%20#console-scripts) entry points (see below).

Thus, replacing `scripts` with `console_scripts` in `setup.py` should fix the issue, e.g.:
```
  entry_points={
        'console_scripts': [
            'btac=btac.main',
        ],
    },
```

**Comment by dlesbre** [comment]
Thanks for reporting this!
I pushed a new version (1.1.4) with your suggested fix.

**Comment by schulzch** [comment]
You're welcome. Did you test it? I think it should be `"console_scripts": ["btac=bibtexautocomplete.core.main:main"]` (sorry for not being precise!).

**Comment by dlesbre** [comment]
Hmm perhaps... it worked on my machine but that might have been an older version of the script file. I'm not home right now but I'll look into it Tuesday.

**Comment by dlesbre** [comment]
So there was indeed a bad setup configuration, I pushed a new version 1.1.5 with a good config.
